const GET_POKEMONS = 'GET_POKEMONS';
const GET_TYPES = 'GET_TYPES';
const FILTER_TYPES = 'FILTER_TYPES';
const FILTER_DB = 'FILTER_DB';
const ALPHABETICAL_ORDER = 'ALPHABETICAL_ORDER';
const ATTACK_ORDER = 'ATTACK_ORDER';

export {
    GET_POKEMONS,
    GET_TYPES,
    FILTER_TYPES,
    FILTER_DB,
    ALPHABETICAL_ORDER,
    ATTACK_ORDER,
}