const GET_POKEMONS = 'GET_POKEMONS';
const GET_TYPES = 'GET_TYPES';
const FILTER_TYPES = 'FILTER_TYPES';
const FILTER_DB = 'FILTER_DB';
const ALPHABETICAL_ORDER = 'ALPHABETICAL_ORDER';
const ATTACK_ORDER = 'ATTACK_ORDER';
const GET_POKEMONS_QUERY = 'GET_POKEMONS_QUERY';
const POST_POKEMON = 'POST_POKEMON';
const GET_DETAILS = 'GET_DETAILS';

export {
    GET_POKEMONS,
    GET_TYPES,
    FILTER_TYPES,
    FILTER_DB,
    ALPHABETICAL_ORDER,
    ATTACK_ORDER,
    GET_POKEMONS_QUERY,
    POST_POKEMON,
    GET_DETAILS
}